package studio.fantasyit.ether_craft;

import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.event.config.ModConfigEvent;
import net.neoforged.neoforge.common.ModConfigSpec;

import java.util.List;

@EventBusSubscriber(modid = EtherCraft.MODID)
public class Config {
    private static final ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();

    // ===== ether — Core ether mechanics =====

    private static final ModConfigSpec.IntValue ETHER_CONVERT = BUILDER
            .comment("How many ether value to gain from one ether item")
            .defineInRange("ether.convert", 100, 1, Integer.MAX_VALUE);

    private static final ModConfigSpec.IntValue ETHER_INACTIVATE_CONVERT_TICK = BUILDER
            .comment("Ticks an ether item entity must wait before auto-converting to inactivated ether")
            .defineInRange("ether.inactivate_convert_tick", 100, 1, Integer.MAX_VALUE);

    // ===== node — Ether Adapt Node =====

    private static final ModConfigSpec.IntValue NODE_DEFAULT_MAX_ETHER = BUILDER
            .comment("Default max ether value of Ether Adapt Node")
            .defineInRange("node.default_max_ether", 6400, 1, Integer.MAX_VALUE);

    private static final ModConfigSpec.ConfigValue<List<? extends Integer>> NODE_UPGRADE_SLOTS = BUILDER
            .comment("Number of upgrade slots per level")
            .defineList("node.upgrade_slots", () -> List.of(2, 4, 6), () -> 0, t -> {
                try {
                    if (t instanceof Integer) return true;
                    Integer.parseInt(t.toString());
                    return true;
                } catch (NumberFormatException e) {
                    return false;
                }
            });

    // -- node.furnace --

    private static final ModConfigSpec.IntValue NODE_FURNACE_BURN_TIME_FACTOR = BUILDER
            .comment("Divisor applied to item burn time (higher = faster fuel consumption)")
            .defineInRange("node.furnace.burn_time_factor", 1, 1, 100);

    private static final ModConfigSpec.IntValue NODE_FURNACE_ETHER_PER_TICK = BUILDER
            .comment("Ether generated per tick while furnace is actively burning fuel")
            .defineInRange("node.furnace.ether_per_tick", 25, 1, Integer.MAX_VALUE);

    private static final ModConfigSpec.IntValue NODE_BLAST_FURNACE_ETHER_PER_TICK = BUILDER
            .comment("Ether generated per tick while blast furnace is actively burning fuel")
            .defineInRange("node.furnace.ether_per_tick_blast_furnace", 50, 1, Integer.MAX_VALUE);
    private static final ModConfigSpec.IntValue NODE_BLAST_FURNACE_BURN_TIME_FACTOR = BUILDER
            .comment("Divisor applied to item burn time (higher = faster fuel consumption)")
            .defineInRange("node.furnace.burn_time_factor_blast_furnace", 1, 1, 100);

    // -- node.magnet --

    private static final ModConfigSpec.IntValue NODE_MAGNET_ETHER_PER_STACK = BUILDER
            .comment("Ether consumed by magnet function when picking up one stack of items")
            .defineInRange("node.magnet.ether_per_stack", 100, 1, Integer.MAX_VALUE);

    // -- node.container_interact --

    private static final ModConfigSpec.IntValue NODE_CONTAINER_INTERACT_ETHER_PER_ITEM = BUILDER
            .comment("Ether consumed per item transferred by ContainerInteract feature")
            .defineInRange("node.container_interact.ether_per_item", 10, 1, Integer.MAX_VALUE);

    // -- node.dropper_thrower --

    private static final ModConfigSpec.IntValue NODE_DROPPER_THROWER_ETHER_PER_ITEM = BUILDER
            .comment("Ether consumed per item thrown by DropperThrower feature")
            .defineInRange("node.dropper_thrower.ether_per_item", 10, 1, Integer.MAX_VALUE);

    // -- node.process --

    private static final ModConfigSpec.IntValue NODE_PROCESS_MAX_PROGRESS = BUILDER
            .comment("Max progress ticks for Node Process function to complete one recipe")
            .defineInRange("node.process.max_progress", 100, 1, Integer.MAX_VALUE);

    // -- node.ether_converter --

    private static final ModConfigSpec.IntValue NODE_ETHER_CONVERTER_COEFFICIENT = BUILDER
            .comment("Ether generated per item consumed by the Ether Converter function plugin")
            .defineInRange("node.ether_converter.coefficient", 100, 1, Integer.MAX_VALUE);

    // -- node.equipment_generator --

    private static final ModConfigSpec.IntValue NODE_EQUIPMENT_GENERATOR_COEFFICIENT = BUILDER
            .comment("Coefficient for ether generation from equipment consumption in Equipment Generator plugin")
            .defineInRange("node.equipment_generator.coefficient", 10, 1, 10000);
    private static final ModConfigSpec.IntValue NODE_EQUIPMENT_GENERATOR_BASE_AMOUNT = BUILDER
            .comment("Base amount of ether generated by Equipment Generator plugin")
            .defineInRange("node.equipment_generator.base_amount", 1, 1, Integer.MAX_VALUE);

    // -- node.growth_accelerator --

    private static final ModConfigSpec.IntValue NODE_GROWTH_ACCELERATOR_ETHER_COST = BUILDER
            .comment("Ether consumed per crop block accelerated by GrowthAccelerator function plugin")
            .defineInRange("node.growth_accelerator.ether_cost", 100, 1, Integer.MAX_VALUE);

    private static final ModConfigSpec.IntValue NODE_GROWTH_ACCELERATOR_RANGE = BUILDER
            .comment("Manhattan distance range for GrowthAccelerator to scan for eligible crop blocks")
            .defineInRange("node.growth_accelerator.range", 1, 1, 16);

    // -- node.emitter --

    private static final ModConfigSpec.IntValue NODE_EMITTER_MIN_ETHER_MIN = BUILDER
            .comment("Minimum bound for the emitter minimum ether slider")
            .defineInRange("node.emitter.min_ether.min", 0, 0, Integer.MAX_VALUE);

    private static final ModConfigSpec.IntValue NODE_EMITTER_MIN_ETHER_MAX = BUILDER
            .comment("Maximum bound for the emitter minimum ether slider")
            .defineInRange("node.emitter.min_ether.max", 100000, 0, Integer.MAX_VALUE);

    // -- node.enchanter --

    private static final ModConfigSpec.ConfigValue<List<? extends Integer>> NODE_ENCHANTER_ETHER_COSTS = BUILDER
            .comment("Ether cost for Enchanter plugin levels 1, 2, and 3")
            .defineList("node.enchanter.ether_costs", () -> List.of(1000, 3000, 9000), () -> 0, t -> {
                try {
                    if (t instanceof Integer) return true;
                    Integer.parseInt(t.toString());
                    return true;
                } catch (NumberFormatException e) {
                    return false;
                }
            });

    private static final ModConfigSpec.IntValue NODE_ENCHANTER_MAX_PROGRESS = BUILDER
            .comment("Max progress ticks for Enchanter plugin to complete enchanting (20 ticks = 1 second)")
            .defineInRange("node.enchanter.max_progress", 100, 1, Integer.MAX_VALUE);

    // ===== ether_stream — Ether Stream entity =====

    private static final ModConfigSpec.IntValue ETHER_STREAM_MAX_TICK = BUILDER
            .comment("Maximum lifetime of an Ether Stream entity in ticks (20 ticks = 1 second)")
            .defineInRange("ether_stream.max_tick", 12000, 1, Integer.MAX_VALUE);

    private static final ModConfigSpec.DoubleValue ETHER_STREAM_CONSUMPTION_FACTOR = BUILDER
            .comment("Base ether consumption per tick as a fraction of total ether stored in the stream")
            .defineInRange("ether_stream.consumption_factor", 0.005, 0, 10);

    private static final ModConfigSpec.DoubleValue ETHER_STREAM_CONSUMPTION_BY_TIME_FACTOR = BUILDER
            .comment("Additional ether consumption factor added per tick of the stream's lifetime (accumulates over time)")
            .defineInRange("ether_stream.consumption_factor_by_time", 0.0001, 0, 10);

    private static final ModConfigSpec.IntValue ETHER_GLASS_PREVENT_CONSUME = BUILDER
            .comment("...")
            .defineInRange("ether_stream.ether_glass_prevent_consume", 20, 0, Integer.MAX_VALUE);

    // -- ether_stream.break_block --

    private static final ModConfigSpec.IntValue ETHER_STREAM_BREAK_BLOCK_HARDNESS_MULTIPLIER = BUILDER
            .comment("Multiplier for block hardness in ether cost calculation per block break")
            .defineInRange("ether_stream.break_block.hardness_multiplier", 20, 1, Integer.MAX_VALUE);

    private static final ModConfigSpec.IntValue ETHER_STREAM_BREAK_BLOCK_EFFICIENCY_DIVISOR = BUILDER
            .comment("Ether cost reduction per level of Efficiency enchantment when breaking blocks")
            .defineInRange("ether_stream.break_block.efficiency_divisor", 3, 0, Integer.MAX_VALUE);

    private static final ModConfigSpec.IntValue ETHER_STREAM_BREAK_BLOCK_CONSTANT_COST = BUILDER
            .comment("Flat ether cost added to every block break on top of the hardness-based formula")
            .defineInRange("ether_stream.break_block.constant_cost", 0, 0, Integer.MAX_VALUE);

    // -- ether_stream.damage --

    private static final ModConfigSpec.IntValue ETHER_STREAM_DAMAGE_ETHER_MULTIPLIER = BUILDER
            .comment("Ether consumed per point of damage dealt by Ether Stream")
            .defineInRange("ether_stream.damage.ether_multiplier", 5, 1, Integer.MAX_VALUE);

    private static final ModConfigSpec.IntValue ETHER_STREAM_DAMAGE_CONSTANT_COST = BUILDER
            .comment("Flat ether cost added to every damage instance on top of the damage-based formula")
            .defineInRange("ether_stream.damage.constant_cost", 0, 0, Integer.MAX_VALUE);

    // -- ether_stream.growth_accelerator --

    private static final ModConfigSpec.IntValue ETHER_STREAM_GROWTH_ACCELERATOR_ETHER_COST = BUILDER
            .comment("Ether consumed per crop block accelerated by Ether Stream Growth Accelerator capability")
            .defineInRange("ether_stream.growth_accelerator.ether_cost", 100, 1, Integer.MAX_VALUE);

    // -- ether_stream.upgrade --
    private static final ModConfigSpec.DoubleValue ETHER_STORAGE_MULTIPLIER = BUILDER
            .comment("The multipiler each ether storage upgrade plugin will provide")
            .defineInRange("node.upgrade.ether_storage_multipiler", 2.5, 1, 200);

    public static final ModConfigSpec.IntValue ETHER_PROCESS_ETHER_CONSUME_PRE_UNMATCHED = BUILDER
            .comment("The ether consumed per tick before the node process upgrade is matched")
            .defineInRange("node.process.ether_consume_pre_unmatched", 1, 0, Integer.MAX_VALUE);

    // ===== plating =====

    private static final ModConfigSpec.IntValue PLATING_DURATION_TICKS = BUILDER
            .comment("Duration in ticks for plating to complete (20 ticks = 1 second)")
            .defineInRange("plating.duration_ticks", 100, 1, 12000);


    static final ModConfigSpec SPEC = BUILDER.build();

    public static int etherConvert;
    public static int etherInactivateConvertTick;
    public static int nodeDefaultMaxEther;
    public static List<Integer> nodeUpgradeSlots;
    public static int nodeFurnaceBurnTimeFactor;
    public static int nodeFurnaceEtherPerTick;
    public static int nodeBlastFurnaceBurnTimeFactor;
    public static int nodeBlastFurnaceEtherPerTick;
    public static int nodeMagnetEtherPerStack;
    public static int nodeContainerInteractEtherPerItem;
    public static int nodeDropperThrowerEtherPerItem;
    public static int nodeProcessMaxProgress;
    public static int nodeEtherConverterCoefficient;
    public static int nodeEquipmentGeneratorCoefficient;
    public static int nodeEquipmentGeneratorBaseAmount;
    public static int nodeGrowthAcceleratorEtherCost;
    public static int nodeGrowthAcceleratorRange;
    public static int nodeEmitterMinEtherMin;
    public static int nodeEmitterMinEtherMax;
    public static int etherStreamMaxTick;
    public static double etherStreamConsumptionFactor;
    public static double etherStreamConsumptionByTimeFactor;
    public static int etherStreamBreakBlockHardnessMultiplier;
    public static int etherStreamBreakBlockEfficiencyDivisor;
    public static int etherStreamBreakBlockConstantCost;
    public static int etherStreamDamageEtherMultiplier;
    public static int etherStreamDamageConstantCost;
    public static int etherStreamGrowthAcceleratorEtherCost;
    public static List<Integer> nodeEnchanterEtherCosts;
    public static int nodeEnchanterMaxProgress;
    public static double etherStorageMultiplier;
    public static int etherGlassPreventConsume;
    public static int nodeProcessEtherConsumePreUnmatched;
    public static int platingDurationTicks;

    @SubscribeEvent
    static void onLoad(final ModConfigEvent event) {
        etherConvert = ETHER_CONVERT.get();
        etherInactivateConvertTick = ETHER_INACTIVATE_CONVERT_TICK.get();
        nodeDefaultMaxEther = NODE_DEFAULT_MAX_ETHER.get();
        nodeUpgradeSlots = NODE_UPGRADE_SLOTS.get().stream().map(t -> (Integer) t).toList();
        nodeFurnaceBurnTimeFactor = NODE_FURNACE_BURN_TIME_FACTOR.get();
        nodeFurnaceEtherPerTick = NODE_FURNACE_ETHER_PER_TICK.get();
        nodeBlastFurnaceBurnTimeFactor = NODE_BLAST_FURNACE_BURN_TIME_FACTOR.get();
        nodeBlastFurnaceEtherPerTick = NODE_BLAST_FURNACE_ETHER_PER_TICK.get();
        nodeMagnetEtherPerStack = NODE_MAGNET_ETHER_PER_STACK.get();
        nodeContainerInteractEtherPerItem = NODE_CONTAINER_INTERACT_ETHER_PER_ITEM.get();
        nodeDropperThrowerEtherPerItem = NODE_DROPPER_THROWER_ETHER_PER_ITEM.get();
        nodeProcessMaxProgress = NODE_PROCESS_MAX_PROGRESS.get();
        nodeEtherConverterCoefficient = NODE_ETHER_CONVERTER_COEFFICIENT.get();
        nodeEquipmentGeneratorCoefficient = NODE_EQUIPMENT_GENERATOR_COEFFICIENT.get();
        nodeEquipmentGeneratorBaseAmount = NODE_EQUIPMENT_GENERATOR_BASE_AMOUNT.get();
        nodeGrowthAcceleratorEtherCost = NODE_GROWTH_ACCELERATOR_ETHER_COST.get();
        nodeGrowthAcceleratorRange = NODE_GROWTH_ACCELERATOR_RANGE.get();
        nodeEmitterMinEtherMin = NODE_EMITTER_MIN_ETHER_MIN.get();
        nodeEmitterMinEtherMax = NODE_EMITTER_MIN_ETHER_MAX.get();
        etherStreamMaxTick = ETHER_STREAM_MAX_TICK.get();
        etherStreamConsumptionFactor = ETHER_STREAM_CONSUMPTION_FACTOR.get();
        etherStreamConsumptionByTimeFactor = ETHER_STREAM_CONSUMPTION_BY_TIME_FACTOR.get();
        etherStreamBreakBlockHardnessMultiplier = ETHER_STREAM_BREAK_BLOCK_HARDNESS_MULTIPLIER.get();
        etherStreamBreakBlockEfficiencyDivisor = ETHER_STREAM_BREAK_BLOCK_EFFICIENCY_DIVISOR.get();
        etherStreamBreakBlockConstantCost = ETHER_STREAM_BREAK_BLOCK_CONSTANT_COST.get();
        etherStreamDamageEtherMultiplier = ETHER_STREAM_DAMAGE_ETHER_MULTIPLIER.get();
        etherStreamDamageConstantCost = ETHER_STREAM_DAMAGE_CONSTANT_COST.get();
        etherStreamGrowthAcceleratorEtherCost = ETHER_STREAM_GROWTH_ACCELERATOR_ETHER_COST.get();
        nodeEnchanterEtherCosts = NODE_ENCHANTER_ETHER_COSTS.get().stream().map(t -> (Integer) t).toList();
        nodeEnchanterMaxProgress = NODE_ENCHANTER_MAX_PROGRESS.get();
        etherStorageMultiplier = ETHER_STORAGE_MULTIPLIER.get();
        etherGlassPreventConsume = ETHER_GLASS_PREVENT_CONSUME.get();
        nodeProcessEtherConsumePreUnmatched = ETHER_PROCESS_ETHER_CONSUME_PRE_UNMATCHED.get();
        platingDurationTicks = PLATING_DURATION_TICKS.get();
    }
}
