package studio.fantasyit.ether_craft.menu.node;

import net.minecraft.resources.Identifier;
import studio.fantasyit.ether_craft.EtherCraft;
import studio.fantasyit.ether_craft.menu.base.ImageAsset;

public class EtherAdaptNodeAsset {
    public static final Identifier BACKGROUND = EtherCraft.id("textures/gui/ether_adapt_node_main.png");
    public static final ImageAsset UI_BASE = new ImageAsset(BACKGROUND, 0, 0, 176, 228);
    public static final ImageAsset ETHER_BAR_CTR = ImageAsset.from4Point(BACKGROUND, 196, 26, 215, 29);
    public static final ImageAsset SLOT = ImageAsset.from4Point(BACKGROUND, 176, 54, 193, 71);
    public static final ImageAsset SLOT_ETHER = ImageAsset.from4Point(BACKGROUND, 176, 72, 195, 91);
    public static final ImageAsset SLOT_LARGE = ImageAsset.from4Point(BACKGROUND, 196, 72, 215, 91);
    public static final ImageAsset LOCK = ImageAsset.from4Point(BACKGROUND, 176, 34, 187, 45);
    public static final ImageAsset INFO_PANEL = new ImageAsset(BACKGROUND, 189, 43, 3, 3);
    public static final ImageAsset PENCIL_ON = ImageAsset.from4Point(BACKGROUND, 176, 46, 183, 53);
    public static final ImageAsset PENCIL_OFF = ImageAsset.from4Point(BACKGROUND, 184, 46, 191, 53);
    public static final ImageAsset HAMMER = ImageAsset.from4Point(BACKGROUND, 197, 34, 211, 48);
    public static final ImageAsset BTN_WHITE = ImageAsset.from4Point(BACKGROUND, 176, 92, 191, 107);
    public static final ImageAsset BTN_WHITE_HOVER = ImageAsset.gridOffset(BTN_WHITE, 1, 0);
    public static final ImageAsset BTN_BLACK = ImageAsset.gridOffset(BTN_WHITE, 0, 1);
    public static final ImageAsset BTN_BLACK_HOVER = ImageAsset.gridOffset(BTN_WHITE_HOVER, 0, 1);
    public static final ImageAsset BTN_BLANK = ImageAsset.gridOffset(BTN_WHITE, 0, 2);
    public static final ImageAsset BTN_BLANK_HOVER = ImageAsset.gridOffset(BTN_WHITE_HOVER, 0, 2);
    public static final ImageAsset BTN_BLANK_DOWN = ImageAsset.gridOffset(BTN_BLANK, 0, 1);
    public static final ImageAsset BTN_BLANK_DOWN_HOVER = ImageAsset.gridOffset(BTN_BLANK, 1, 1);
    public static final ImageAsset BTN_ICON_U = ImageAsset.gridOffset(BTN_BLANK_DOWN, 0, 1);
    public static final ImageAsset BTN_ICON_D = ImageAsset.gridOffset(BTN_BLANK_DOWN, 1, 1);
    public static final ImageAsset BTN_ICON_W = ImageAsset.gridOffset(BTN_BLANK_DOWN, 0, 2);
    public static final ImageAsset BTN_ICON_S = ImageAsset.gridOffset(BTN_BLANK_DOWN, 1, 2);
    public static final ImageAsset BTN_ICON_N = ImageAsset.gridOffset(BTN_BLANK_DOWN, 0, 3);
    public static final ImageAsset BTN_ICON_E = ImageAsset.gridOffset(BTN_BLANK_DOWN, 1, 3);
    public static final ImageAsset BTN_ICON_EXTRACT = ImageAsset.gridOffset(BTN_BLANK_DOWN, 0, 4);
    public static final ImageAsset BTN_ICON_INSERT = ImageAsset.gridOffset(BTN_BLANK_DOWN, 1, 4);
    public static final ImageAsset BTN_ICON_ETHER = ImageAsset.gridOffset(BTN_BLANK_DOWN, 0, 5);
    public static final ImageAsset BTN_ICON_CONTAINER = ImageAsset.gridOffset(BTN_BLANK_DOWN, 1, 5);
    public static final ImageAsset BTN_ICON_REDSTONE_INVERT = ImageAsset.gridOffset(BTN_BLANK_DOWN, 0, 6);
    public static final ImageAsset BTN_ICON_REDSTONE = ImageAsset.gridOffset(BTN_BLANK_DOWN, 1, 6);
    public static final ImageAsset ICON_UPGRADE = ImageAsset.from4Point(BACKGROUND, 212, 31, 223, 42);
    public static final ImageAsset SCROLL_BLOCK = ImageAsset.from4Point(BACKGROUND, 208, 92, 217, 104);
    public static final ImageAsset SCROLL_BLOCK_HOVER = ImageAsset.from4Point(BACKGROUND, 208, 156, 217, 168);
    public static final ImageAsset SCROLL_BACK = ImageAsset.from4Point(BACKGROUND, 208, 105, 211, 155);
    public static final ImageAsset ARROW_RIGHT = ImageAsset.from4Point(BACKGROUND, 224, 36, 234, 43);
    public static final ImageAsset ARROW_LEFT = ImageAsset.from4Point(BACKGROUND, 224, 44, 234, 51);
    public static final ImageAsset PROGRESS_INDICATOR = ImageAsset.from4Point(BACKGROUND, 218, 72, 238, 85);
    public static final ImageAsset PROGRESS_INDICATOR_FILL = ImageAsset.from4Point(BACKGROUND, 218, 86, 238, 101);
    public static final ImageAsset SLOT_RESULT_INDICATOR = ImageAsset.from4Point(BACKGROUND, 212, 54, 229, 71);
    public static final ImageAsset SLOT_RESULT_INDICATOR_HOVER = ImageAsset.from4Point(BACKGROUND, 230, 54, 247, 71);
    public static final ImageAsset FILTER_PANEL = ImageAsset.from4Point(BACKGROUND, 224, 0, 249, 35);
    public static final ImageAsset FILTER_ICON = ImageAsset.from4Point(BACKGROUND, 233, 23, 240, 31);
    public static final ImageAsset ENCHANT_BTN_NORMAL = ImageAsset.from4Point(BACKGROUND, 212, 105, 227, 120);
    public static final ImageAsset ENCHANT_BTN_DOWN = ImageAsset.gridOffset(ENCHANT_BTN_NORMAL, 0, 1);
    public static final ImageAsset ENCHANT_BTN_HOVER = ImageAsset.gridOffset(ENCHANT_BTN_NORMAL, 0, 2);

    public static final ImageAsset ENCHANT_ICON_LV1 = ImageAsset.from4Point(BACKGROUND, 229, 108, 240, 116);
    public static final ImageAsset ENCHANT_ICON_LV2 = ImageAsset.from4Point(BACKGROUND, 229, 123, 240, 133);
    public static final ImageAsset ENCHANT_ICON_LV3 = ImageAsset.from4Point(BACKGROUND, 229, 139, 240, 149);
    public static final ImageAsset ENCHANT_ICON_LV1_DISABLED = ImageAsset.from4Point(BACKGROUND, 242, 108, 253, 116);
    public static final ImageAsset ENCHANT_ICON_LV2_DISABLED = ImageAsset.from4Point(BACKGROUND, 242, 123, 253, 133);
    public static final ImageAsset ENCHANT_ICON_LV3_DISABLED = ImageAsset.from4Point(BACKGROUND, 242, 139, 253, 149);
}
