package studio.fantasyit.ether_craft.recipe.factory.multistep;

import net.minecraft.world.item.ItemStack;
import net.neoforged.neoforge.common.crafting.SizedIngredient;
import studio.fantasyit.ether_craft.base.TreeLike;
import studio.fantasyit.ether_craft.recipe.factory.EtherProcessFactoryRecipe;
import studio.fantasyit.ether_craft.util.MathUtil;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MultiStepMatchIOTemp {
    private List<SizedIngredient> inputs = new ArrayList<>();
    private List<ItemStack> outputs = new ArrayList<>();
    private List<ItemStack> extraOutputs = new ArrayList<>();

    private List<Integer> inputBelongsTo = new ArrayList<>();
    private List<Integer> outputBelongsTo = new ArrayList<>();
    private List<Integer> extraOutputsBelongsTo = new ArrayList<>();

    private Map<Integer, Integer> nodeMultipliersInner = new HashMap<>();
    private Map<Integer, Integer> nodeMultipliersOuter = new HashMap<>();


    public void addInput(SizedIngredient stack, int outId) {
        inputs.add(stack);
        inputBelongsTo.add(outId);
    }

    public void addOutput(ItemStack stack, int outId) {
        outputs.add(stack);
        outputBelongsTo.add(outId);
    }

    public void addExtraOutput(ItemStack stack, int outId) {
        extraOutputs.add(stack);
        extraOutputsBelongsTo.add(outId);
    }

    public void setNodeMultiplierInner(int outId, int multiplier) {
        nodeMultipliersInner.put(outId, multiplier);
    }

    public void setNodeMultiplierOuter(int outId, int multiplier) {
        nodeMultipliersOuter.put(outId, multiplier);
    }

    public MultiStepMatchIO propagateMultipliersAndGetImmutable(TreeLike<EtherFactoryMultiStepInput.TreeRef, Integer> treeLike, TreeLike<EtherProcessFactoryRecipe, Void> key) {
        Map<Integer, Integer> finalMultipliers = new HashMap<>();
        int optimal = computeRequiredFactor(treeLike.getRoot());
        propagateMultipliersDFS(treeLike.getRoot(), finalMultipliers, optimal);
        List<SizedIngredient> finalInputs = new ArrayList<>();
        List<ItemStack> finalOutputs = new ArrayList<>();
        for (int i = 0; i < inputs.size(); i++) {
            SizedIngredient sizedIngredient = new SizedIngredient(inputs.get(i).ingredient(), finalMultipliers.getOrDefault(inputBelongsTo.get(i), 1) * inputs.get(i).count());
            finalInputs.add(sizedIngredient);
        }
        for (int i = 0; i < outputs.size(); i++) {
            finalOutputs.add(outputs.get(i).copyWithCount(finalMultipliers.getOrDefault(outputBelongsTo.get(i), 1) * outputs.get(i).getCount()));
        }
        for (int i = 0; i < extraOutputs.size(); i++) {
            finalOutputs.add(extraOutputs.get(i).copyWithCount(finalMultipliers.getOrDefault(extraOutputsBelongsTo.get(i), 1) * extraOutputs.get(i).getCount()));
        }
        return new MultiStepMatchIO(finalInputs, finalOutputs, key, nodeMultipliersInner.values().stream().max(Integer::compareTo).orElse(1));
    }

    private void propagateMultipliersDFS(TreeLike.TreeNode<EtherFactoryMultiStepInput.TreeRef, Integer> node, Map<Integer, Integer> finalMultipliers, int multiplier) {
        int nodeId = node.value.output();
        int innerMul = nodeMultipliersInner.getOrDefault(nodeId, 1);

        int finalMul = ((multiplier + innerMul - 1) / innerMul) * innerMul;
        finalMultipliers.put(nodeId, finalMul);

        int parentInner = nodeMultipliersInner.getOrDefault(nodeId, 1);
        for (var edge : node.edges) {
            int childId = edge.node.value.output();
            int outer = nodeMultipliersOuter.getOrDefault(childId, 1);
            int childReq = finalMul * outer / parentInner;
            propagateMultipliersDFS(edge.node, finalMultipliers, childReq);
        }
    }

    /**
     * 返回：为了让当前节点及其子树不发生向上取整，
     * 当前节点被传入的 multiplier 必须是此返回值的倍数。
     * Generated By deepseek
     */
    private int computeRequiredFactor(
            TreeLike.TreeNode<EtherFactoryMultiStepInput.TreeRef, Integer> node) {

        int nodeId = node.value.output();
        int inner = nodeMultipliersInner.getOrDefault(nodeId, 1);

        // 基础要求：自身 inner 的倍数
        int required = inner;

        for (var edge : node.edges) {
            int childId = edge.node.value.output();
            int childInner = nodeMultipliersInner.getOrDefault(childId, 1);
            int outer = nodeMultipliersOuter.getOrDefault(childId, 1);
            int parentInner = nodeMultipliersInner.getOrDefault(nodeId, 1);

            // 子节点需求 = multiplier * outer / parentInner
            // 要求该需求是 childInner 的倍数 → multiplier 必须整除 (parentInner * childInner) / gcd(outer, childInner)
            int step = parentInner * childInner / MathUtil.findGCD(outer, childInner);
            required = MathUtil.findLCM(required, step);

            // 此外，子节点自己的子树也有要求（返回的是对子节点 multiplier 的约束）
            int childReqOnItsOwnMultiplier = computeRequiredFactor(edge.node);
            // 子节点要求它的 multiplier 是 childReqOnItsOwnMultiplier 的倍数
            // 它的 multiplier = 父 multiplier * outer / parentInner
            // 所以父 multiplier 必须整除 (parentInner * childReqOnItsOwnMultiplier) / gcd(outer, childReqOnItsOwnMultiplier)
            int step2 = parentInner * childReqOnItsOwnMultiplier / MathUtil.findGCD(outer, childReqOnItsOwnMultiplier);
            required = MathUtil.findLCM(required, step2);
        }
        return required;
    }

}
